version: "3.9"
services:
  django:
    build: .
    container_name: wisetrade-api
    env_file: .env.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: wisetrade
      POSTGRES_USER: wisetrade
      POSTGRES_PASSWORD: wisetrade
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  pgdata:
