services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'trade_smart_api'
      POSTGRES_USER: 'trade_smart_api'
      POSTGRES_DB: 'trade_smart_api'
    volumes:
      - ./data:/var/lib/postgresql/data
  chroma:
      image: ghcr.io/chroma-core/chroma:1.0.16.dev44
      volumes: [ "chroma-data:/chroma" ]
      ports: [ "8002:8000" ]

  ollama:
      image: ollama/ollama:0.1.41
      tty: true
      volumes: [ "ollama:/root/.ollama" ]
      environment:
        - OLLAMA_MODELS=llama2:13b


volumes:
    chroma-data:
    ollama:
