# Generated by Django 5.2.4 on 2025-07-12 11:07

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10)),
                ("date", models.DateField(db_index=True)),
                ("open", models.DecimalField(decimal_places=4, max_digits=20)),
                ("high", models.DecimalField(decimal_places=4, max_digits=20)),
                ("low", models.DecimalField(decimal_places=4, max_digits=20)),
                ("close", models.DecimalField(decimal_places=4, max_digits=20)),
                ("volume", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
