# Generated by Django 5.2.4 on 2025-07-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0002_marketdata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marketdata",
            options={"ordering": ("-date",)},
        ),
        migrations.AlterUniqueTogether(
            name="marketdata",
            unique_together={("ticker", "date")},
        ),
    ]
