# Generated by Django 5.2.4 on 2025-07-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0003_alter_marketdata_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MarketData",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="position",
            name="created_at",
        ),
    ]
