# Generated by Django 5.2.4 on 2025-07-13 14:58

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0005_marketdata_technicalindicator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("ticker", models.CharField(blank=True, max_length=10)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("BUY", "BUY"),
                            ("SELL", "SELL"),
                            ("HOLD", "HOLD"),
                            ("REBAL", "REBALANCE"),
                        ],
                        max_length=5,
                    ),
                ),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("rationale", models.TextField()),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advices",
                        to="trade_smart.portfolio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
