# Generated by Django 5.2.4 on 2025-07-13 19:30

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0006_advice"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=12)),
                ("headline", models.TextField()),
                ("source", models.CharField(max_length=60)),
                ("url", models.URLField(max_length=300)),
                ("published_at", models.DateTimeField(db_index=True)),
                (
                    "sentiment",
                    models.DecimalField(decimal_places=3, max_digits=4, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "-published_at"],
                        name="trade_smart_ticker_c17f22_idx",
                    )
                ],
            },
        ),
    ]
