# Generated by Django 5.2.4 on 2025-07-23 15:42

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0007_newsarticle"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=12)),
                ("score", models.DecimalField(decimal_places=3, max_digits=4)),
                ("summary", models.TextField()),
            ],
            options={
                "verbose_name": "LLM Sentiment",
                "verbose_name_plural": "LLM Sentiments",
                "ordering": ["-created"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="newsarticle",
            unique_together={("url", "published_at")},
        ),
    ]
