# Generated by Django 5.2.4 on 2025-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0008_llmsentiment_alter_newsarticle_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
