# Generated by Django 5.2.4 on 2025-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0009_newsarticle_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketdata",
            name="ticker",
            field=models.CharField(db_index=True, max_length=25),
        ),
    ]
