# Generated by Django 5.2.4 on 2025-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0010_alter_marketdata_ticker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advice",
            name="ticker",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="technicalindicator",
            name="ticker",
            field=models.CharField(db_index=True, max_length=25),
        ),
    ]
