# Generated by Django 5.2.4 on 2025-08-03 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0011_alter_advice_ticker_alter_technicalindicator_ticker"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advice",
            name="portfolio",
        ),
        migrations.AddField(
            model_name="advice",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advice",
            name="weight_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="advice",
            name="action",
            field=models.CharField(
                choices=[("BUY", "BUY"), ("SELL", "SELL"), ("HOLD", "HOLD")],
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="advice",
            name="confidence",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="advice",
            name="ticker",
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name="InvestmentGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="PLN", max_length=3)),
                ("horizon_months", models.PositiveIntegerField(default=12)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=6,
                    ),
                ),
                ("status", models.CharField(default="NEW", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advice",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trade_smart.investmentgoal",
            ),
        ),
    ]
