# Generated by Django 5.2.4 on 2025-08-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_smart", "0012_remove_advice_portfolio_advice_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="portfolio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advices",
                to="trade_smart.portfolio",
            ),
            preserve_default=False,
        ),
    ]
